Feature2課題
misato-okada/learning_plan pull request #2
Opened 2021-05-09 08:09 UTC by misato-okada

feature2課題終了しました。
確認お願いします。

2021-05-09 09:27 UTC, Arisaarisa commented
課題提出お疲れさまです！
とても細かいですが今回課題条件に`
- 完了期限を過ぎた学習内容は (PHP で算出したシステム日付 >= 期限日) の場合、期限日を赤色に変える`
とあるので、本日の日付も赤色になるよう変更をお願いします！:pray:



またその下の、完了を過ぎた期限の条件に
- `(html のタグ内に class を追加するイメージ。クラス名:expired。style.cssで.expiredに対してカラーをレッドにする。) ※画像参照`
となっているのでその条件に沿っての修正をお願いします！:+1:
functions.phpの中に関数定義してからindex.phpで使用します！

2021-05-09 13:03 UTC, misato-okada commented
feature1のときにも指摘あったのですが、関数定義してから使用する方法がどうしてもわかりません。
以前はできなければタグごと追加する処理でも構わないとのことで、先程のような処理でかいていたのですが、
function.phpにかいてからindex.phpでつかう方法教えていただけますでしょうか？

2021-05-09 20:18 UTC, kazu-taka requested changes
@misato-okada 
コメントしたので確認お願いします:bow:

2021-05-09 20:18 UTC, kazu-taka commented on index.php
> +                                <td class="plan-due-date <?php if ($notyet_plans) echo (expiredDuedate($notyet_plans)); ?>">
@misato-okada 
私が関数化しなくても良い伝えていた件が、運営側で共有されておらずすみません:bow:
`<?php if ($notyet_plans) echo (expiredDuedate($notyet_plans)); ?>`の処理は`<?php foreach ($notyet_plans as $plan): ?>`の中で実行されています。
ですので、例えば未完了タスクが5件あった場合は5回実行される処理となります。
`<?php if ($notyet_plans) echo (expiredDuedate($notyet_plans)); ?>`で渡してる`$notyet_plans`は、未完了タスク全て渡しているので、全て渡すのでなく、`$plan`を渡すようにしてください！
あとは、`expiredDuedate`関数の中で、「今日 > タスクの期限」だった場合、`expired`という文字を返すようにしてあげればOKです👍

2021-05-10 06:28 UTC, kazu-taka commented
@misato-okada 
問題ないのでマージしてOKです👍
![LGTM](https://image.lgtmoon.dev/31829)

2021-05-10 14:17 UTC, merged